version: '3.5'
services:
  db:
    image: mysql:5.7
    container_name: auth-jwt-db
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: auth_sample
      TZ: 'Asia/Tokyo'
    command: mysqld --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci
    volumes:
      # この辺は必要なら適宜
      - ./mysql/init.d:/docker-entrypoint-initdb.d
    ports:
      - 3307:3306
    restart: always